server:
  port: 9898
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    druid:
      filter: stat,wall
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      use-global-data-source-stat: true
      validation-query: select 'x'
    name: xiazy
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: blog
    password: PddAXWf6LrPswyYe
  redis:
    host: 127.0.0.1
    port: 6379
    
logging:
  level:
    com:
      site:
        blog:
          dao: debug

  

  








